DROP TABLE IF EXISTS dbo.Provincia;
GO

CREATE TABLE dbo.Provincia (
	Id int NOT NULL PRIMARY KEY,
	IdCcaa INT NOT NULL FOREIGN KEY REFERENCES dbo.CCAA(Id),
	Descripcion varchar(255) NOT NULL,
	UtmX int NULL,
	UtmY int NULL,
	Huso varchar(3) NULL,
	GeoPosicion GEOMETRY,
	---
    FechaCreacion DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),
	CreadoPor UNIQUEIDENTIFIER NULL,
	FechaModificacion DATETIME2(7) NULL,
	ModificadoPor UNIQUEIDENTIFIER NULL,
	FechaEliminacion DATETIME2(7) NULL,
	EliminadoPor UNIQUEIDENTIFIER NULL,
	Borrado BIT NOT NULL DEFAULT 0
);