//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGPCE.Sigemad.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGPCE.Sigemad.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La lista de áreas afectadas no puede ser nula..
        /// </summary>
        public static string AreaAfectadaNoNulo {
            get {
                return ResourceManager.GetString("AreaAfectadaNoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La lista de áreas afectadas no puede estar vacía..
        /// </summary>
        public static string AreaAfectadaVacio {
            get {
                return ResourceManager.GetString("AreaAfectadaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto no puede superar 500 caracteres.
        /// </summary>
        public static string AsuntoMaxLegth {
            get {
                return ResourceManager.GetString("AsuntoMaxLegth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto es obligatorio.
        /// </summary>
        public static string AsuntoNoNulo {
            get {
                return ResourceManager.GetString("AsuntoNoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto no puede ser vacio.
        /// </summary>
        public static string AsuntoNoVacio {
            get {
                return ResourceManager.GetString("AsuntoNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad no puede exceder 100 caracteres.
        /// </summary>
        public static string AutoridadMaxLength {
            get {
                return ResourceManager.GetString("AutoridadMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad es obligatorio.
        /// </summary>
        public static string AutoridadObligatorio {
            get {
                return ResourceManager.GetString("AutoridadObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad que dirige no puede estar en blanco.
        /// </summary>
        public static string AutoridadQueDirigeEnBlanco {
            get {
                return ResourceManager.GetString("AutoridadQueDirigeEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad Que Dirige es obligatorio.
        /// </summary>
        public static string AutoridadQueDirigeObligatorio {
            get {
                return ResourceManager.GetString("AutoridadQueDirigeObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad solicitante no puede superar los 510 caracteres.
        /// </summary>
        public static string AutoridadSolicitanteMaxLength {
            get {
                return ResourceManager.GetString("AutoridadSolicitanteMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad Solicitante es obligatorio.
        /// </summary>
        public static string AutoridadSolicitanteObligatorio {
            get {
                return ResourceManager.GetString("AutoridadSolicitanteObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase de Suceso es obligatorio.
        /// </summary>
        public static string ClaseSucesoObligatorio {
            get {
                return ResourceManager.GetString("ClaseSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo no puede tener mas de 15 caracteres.
        /// </summary>
        public static string CodigoMaxLength {
            get {
                return ResourceManager.GetString("CodigoMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convocados no puede exceder los 510 caracteres.
        /// </summary>
        public static string ConvocadosMaxLength {
            get {
                return ResourceManager.GetString("ConvocadosMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convocados es obligatorio.
        /// </summary>
        public static string ConvocadosObligatorio {
            get {
                return ResourceManager.GetString("ConvocadosObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La lista de coordinaciones es obligatorio.
        /// </summary>
        public static string CoordinacionesObligatorio {
            get {
                return ResourceManager.GetString("CoordinacionesObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Principal son obligatorios.
        /// </summary>
        public static string DatoPrincipalObligatorio {
            get {
                return ResourceManager.GetString("DatoPrincipalObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denominacion no puede exceder los 255 caracteres.
        /// </summary>
        public static string DenominacionMaxLength {
            get {
                return ResourceManager.GetString("DenominacionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        public static string DenominacionNoVacio {
            get {
                return ResourceManager.GetString("DenominacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denominacion es obligatorio.
        /// </summary>
        public static string DenominacionObligatorio {
            get {
                return ResourceManager.GetString("DenominacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denominación no puede exceder los 510 caracteres.
        /// </summary>
        public static string DenominacionZAGEPMaxLength {
            get {
                return ResourceManager.GetString("DenominacionZAGEPMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion no puede exceder los 255 caracteres.
        /// </summary>
        public static string DescripcionMaxLength {
            get {
                return ResourceManager.GetString("DescripcionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion es obligatorio.
        /// </summary>
        public static string DescripcionObligatorio {
            get {
                return ResourceManager.GetString("DescripcionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Solicitud no puede superar los 510 caracteres.
        /// </summary>
        public static string DescripcionSolicitudMaxLength {
            get {
                return ResourceManager.GetString("DescripcionSolicitudMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Solicitud es obligatorio.
        /// </summary>
        public static string DescripcionSolicitudObligatorio {
            get {
                return ResourceManager.GetString("DescripcionSolicitudObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las lista de direcciones es obligatorio.
        /// </summary>
        public static string DireccionesObligatorio {
            get {
                return ResourceManager.GetString("DireccionesObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad Menor es obligatorio.
        /// </summary>
        public static string EntidadMenorObligatorio {
            get {
                return ResourceManager.GetString("EntidadMenorObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Suceso es obligatorio.
        /// </summary>
        public static string EstadoSucesoObligatorio {
            get {
                return ResourceManager.GetString("EstadoSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolucion es obligatorio.
        /// </summary>
        public static string EvolucionObligatorio {
            get {
                return ResourceManager.GetString("EvolucionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaHoraActivacionObligatorio es obligatorio.
        /// </summary>
        public static string FechaHoraActivacionObligatorio {
            get {
                return ResourceManager.GetString("FechaHoraActivacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaHoraActualizacionObligatorio es obligatorio.
        /// </summary>
        public static string FechaHoraActualizacionObligatorio {
            get {
                return ResourceManager.GetString("FechaHoraActualizacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaHoraNotificacion es obligatorio.
        /// </summary>
        public static string FechaHoraNotificacionObligatorio {
            get {
                return ResourceManager.GetString("FechaHoraNotificacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaHora no puede ser vacio.
        /// </summary>
        public static string FechaHoraNoVacio {
            get {
                return ResourceManager.GetString("FechaHoraNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha hora es obligatoria.
        /// </summary>
        public static string FechaHoraObligatorio {
            get {
                return ResourceManager.GetString("FechaHoraObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaHoraSolicitud es obligatoria.
        /// </summary>
        public static string FechaHoraSolicitudObligatorio {
            get {
                return ResourceManager.GetString("FechaHoraSolicitudObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio debe ser menor que Fecha Fin.
        /// </summary>
        public static string FechaInicioDebeSerMenorQueFechaFin {
            get {
                return ResourceManager.GetString("FechaInicioDebeSerMenorQueFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de inicio no puede ser posterior a la fecha actual..
        /// </summary>
        public static string FechaInicioFutura {
            get {
                return ResourceManager.GetString("FechaInicioFutura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio es obligatoria.
        /// </summary>
        public static string FechaInicioObligatorio {
            get {
                return ResourceManager.GetString("FechaInicioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inicio PMA es obligatoria.
        /// </summary>
        public static string FechaInicioPMAObligatorio {
            get {
                return ResourceManager.GetString("FechaInicioPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaSolicitud es obligatoria.
        /// </summary>
        public static string FechaSolicitudObligatorio {
            get {
                return ResourceManager.GetString("FechaSolicitudObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La geometría CECOPI no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionCECOPInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionCECOPInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeoPosicion CECOPI es obligatoria.
        /// </summary>
        public static string GeoPosicionCECOPIObligatoria {
            get {
                return ResourceManager.GetString("GeoPosicionCECOPIObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La geometría no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeoPosicion es obligatorio.
        /// </summary>
        public static string GeoPosicionObligatorio {
            get {
                return ResourceManager.GetString("GeoPosicionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La geometría PMA no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionPMAInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionPMAInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeoPosicion PMA es obligatorio.
        /// </summary>
        public static string GeoPosicionPMAObligatoria {
            get {
                return ResourceManager.GetString("GeoPosicionPMAObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdArchivo es obligatorio.
        /// </summary>
        public static string IdArchivoObligatorio {
            get {
                return ResourceManager.GetString("IdArchivoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos un valor para IdArchivo o Archivo.
        /// </summary>
        public static string IdArchivoOrArchivo {
            get {
                return ResourceManager.GetString("IdArchivoOrArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdCapacidad es obligatorio.
        /// </summary>
        public static string IdCapacidadObligatorio {
            get {
                return ResourceManager.GetString("IdCapacidadObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdCaracterMedio es obligatorio.
        /// </summary>
        public static string IdCaracterMedioObligatorio {
            get {
                return ResourceManager.GetString("IdCaracterMedioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de lista Entrada/Salida es obligatorio.
        /// </summary>
        public static string IdEntradaSalidaObligatorio {
            get {
                return ResourceManager.GetString("IdEntradaSalidaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de estado incendio es obligatorio.
        /// </summary>
        public static string IdEstadoIncendioObligatorio {
            get {
                return ResourceManager.GetString("IdEstadoIncendioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de lista de medios es obligatorio.
        /// </summary>
        public static string IdMedioObligatorio {
            get {
                return ResourceManager.GetString("IdMedioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id no puede ser vacio.
        /// </summary>
        public static string IdNoVacio {
            get {
                return ResourceManager.GetString("IdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id es obligatorio.
        /// </summary>
        public static string IdObligatorio {
            get {
                return ResourceManager.GetString("IdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Suceso asociado no puede ser vacio.
        /// </summary>
        public static string IdSucesoAsociadoNoVacio {
            get {
                return ResourceManager.GetString("IdSucesoAsociadoNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id suceso asociado es oblogatorio.
        /// </summary>
        public static string IdSucesoAsociadoObligatorio {
            get {
                return ResourceManager.GetString("IdSucesoAsociadoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Suceso es obligatorio.
        /// </summary>
        public static string IdSucesoObligatorio {
            get {
                return ResourceManager.GetString("IdSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Suceso principal no puede ser vacio.
        /// </summary>
        public static string IdSucesoPrincipalNoVacio {
            get {
                return ResourceManager.GetString("IdSucesoPrincipalNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Suceso principal es obligatorio.
        /// </summary>
        public static string IdSucesoPrincipalObligatorio {
            get {
                return ResourceManager.GetString("IdSucesoPrincipalObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Tipo de Direccion es inválido.
        /// </summary>
        public static string IdTipoDireccionEmergenciaInvalido {
            get {
                return ResourceManager.GetString("IdTipoDireccionEmergenciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdTipoDocumento es invalido.
        /// </summary>
        public static string IdTipoDocumentoInvalido {
            get {
                return ResourceManager.GetString("IdTipoDocumentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdTipoDocumento es obligatorio.
        /// </summary>
        public static string IdTipoDocumentoObligatorio {
            get {
                return ResourceManager.GetString("IdTipoDocumentoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdTipoNotificacion es obligatorio.
        /// </summary>
        public static string IdTipoNotificacionObligatorio {
            get {
                return ResourceManager.GetString("IdTipoNotificacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Tipo Sistema de Emergencia es obligatorio.
        /// </summary>
        public static string IdTipoSistemaEmergencia {
            get {
                return ResourceManager.GetString("IdTipoSistemaEmergencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdTitularidadMedio es obligatorio.
        /// </summary>
        public static string IdTitularidadMedioObligatorio {
            get {
                return ResourceManager.GetString("IdTitularidadMedioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Incendio no puede estar vacio.
        /// </summary>
        public static string IncendioIdNoVacio {
            get {
                return ResourceManager.GetString("IncendioIdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Incendio es obligatorio.
        /// </summary>
        public static string IncendioIdObligatorio {
            get {
                return ResourceManager.GetString("IncendioIdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incendio es inválido.
        /// </summary>
        public static string IncendioInvalido {
            get {
                return ResourceManager.GetString("IncendioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incendio es obligatorio.
        /// </summary>
        public static string IncendioObligatorio {
            get {
                return ResourceManager.GetString("IncendioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Otra información es obligatorio.
        /// </summary>
        public static string ListaOtraInformacion {
            get {
                return ResourceManager.GetString("ListaOtraInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El lugar es obligatorio.
        /// </summary>
        public static string LugarObligatorio {
            get {
                return ResourceManager.GetString("LugarObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar no puede exceder los 510 caracteres.
        /// </summary>
        public static string LugarObligatorioMaxLength {
            get {
                return ResourceManager.GetString("LugarObligatorioMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MedioId no puede ser vacio.
        /// </summary>
        public static string MedioIdNoVacio {
            get {
                return ResourceManager.GetString("MedioIdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MedioId es obligatorio.
        /// </summary>
        public static string MedioIdObligatorio {
            get {
                return ResourceManager.GetString("MedioIdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio CECOPI es invalido.
        /// </summary>
        public static string MunicipioCECOPIInvalido {
            get {
                return ResourceManager.GetString("MunicipioCECOPIInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio CECOPI es Obligatorio.
        /// </summary>
        public static string MunicipioCECOPIObligatorio {
            get {
                return ResourceManager.GetString("MunicipioCECOPIObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio es inválido.
        /// </summary>
        public static string MunicipioInvalido {
            get {
                return ResourceManager.GetString("MunicipioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio es obligatorio.
        /// </summary>
        public static string MunicipioObligatorio {
            get {
                return ResourceManager.GetString("MunicipioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio CECOPI es invalido.
        /// </summary>
        public static string MunicipioPMAiInvalido {
            get {
                return ResourceManager.GetString("MunicipioPMAiInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio PMA es Obligatorio.
        /// </summary>
        public static string MunicipioPMAObligatorio {
            get {
                return ResourceManager.GetString("MunicipioPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumeroCapacidades es obligatorio.
        /// </summary>
        public static string NumeroCapacidadesObligatorio {
            get {
                return ResourceManager.GetString("NumeroCapacidadesObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ObservacionesObligatorio es obligatorio.
        /// </summary>
        public static string ObservacionesObligatorio {
            get {
                return ResourceManager.GetString("ObservacionesObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación es obligatorio.
        /// </summary>
        public static string ObservacionObligatorio {
            get {
                return ResourceManager.GetString("ObservacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organos notificados no puede superar los 510 caracteres.
        /// </summary>
        public static string OrganosNotificadosMaxLength {
            get {
                return ResourceManager.GetString("OrganosNotificadosMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organos Notificados es obligatorio.
        /// </summary>
        public static string OrganosNotificadosObligatorio {
            get {
                return ResourceManager.GetString("OrganosNotificadosObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais es inválido.
        /// </summary>
        public static string PaisInvalido {
            get {
                return ResourceManager.GetString("PaisInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais es obligatorio.
        /// </summary>
        public static string PaisObligatorio {
            get {
                return ResourceManager.GetString("PaisObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de parámetros son obligatorio.
        /// </summary>
        public static string ParametroObligatorio {
            get {
                return ResourceManager.GetString("ParametroObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PrevisionObligatorio es obligatorio.
        /// </summary>
        public static string PrevisionObligatorio {
            get {
                return ResourceManager.GetString("PrevisionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de procedencia/Destino es obligatorio.
        /// </summary>
        public static string ProcedenciasDestinosObligatorio {
            get {
                return ResourceManager.GetString("ProcedenciasDestinosObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia CECOPI es invalido.
        /// </summary>
        public static string ProvinciaCECOPIInvalido {
            get {
                return ResourceManager.GetString("ProvinciaCECOPIInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia CECOPI es obligatorio.
        /// </summary>
        public static string ProvinciaCECOPIObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaCECOPIObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia es inválido.
        /// </summary>
        public static string ProvinciaInvalido {
            get {
                return ResourceManager.GetString("ProvinciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia es obligatoria.
        /// </summary>
        public static string ProvinciaObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia PMA es invalido.
        /// </summary>
        public static string ProvinciaPMAInvalido {
            get {
                return ResourceManager.GetString("ProvinciaPMAInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia PMA es obligatorio.
        /// </summary>
        public static string ProvinciaPMAObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Registros son obligatorio.
        /// </summary>
        public static string RegistroObligatorio {
            get {
                return ResourceManager.GetString("RegistroObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        public static string TerritorioInvalido {
            get {
                return ResourceManager.GetString("TerritorioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        public static string TerritorioObligatorio {
            get {
                return ResourceManager.GetString("TerritorioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo dirección emergencia es invalido.
        /// </summary>
        public static string TipoDireccionEmergenciaInvalido {
            get {
                return ResourceManager.GetString("TipoDireccionEmergenciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo dirección emergencia es obligatorio.
        /// </summary>
        public static string TipoDireccionEmergenciaObligatorio {
            get {
                return ResourceManager.GetString("TipoDireccionEmergenciaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación no puede ser vacio.
        /// </summary>
        public static string UbicacionNoVacio {
            get {
                return ResourceManager.GetString("UbicacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación es obligatorio.
        /// </summary>
        public static string UbicacionObligatorio {
            get {
                return ResourceManager.GetString("UbicacionObligatorio", resourceCulture);
            }
        }
    }
}
