/*
export const IDS_TABLAS_CATALOGO_OPE = {
  FASES: 7,
  PERIODOTIPO: 8,
} as const;
*/

import { measureAndCacheTextWidth } from 'ol/render/canvas';

export const IDS_TABLAS_LOGS_OPE = {
  FRONTERAS: 20,
  PUERTOS: 22,
  LINEASMARITIMAS: 23,
  PERIODOS: 24,
  DATOSFRONTERAS: 25,
  DATOSASISTENCIAS: 26,
  DATOSEMBARQUESDIARIOS: 27,
  PUNTOSCONTROLCARRETERAS: 28,
  AREASDESCANSO: 29,
  AREASESTACIONAMIENTO: 30,
  PORCENTAJESOCUPACIONAREASESTACIONAMIENTO: 31,
} as const;

export const NUMEROREGISTROSLOGS: number = 5;

export const CCAA_MEDITERRANEO_ID = {
  CATALUNA: 7,
  COMUNIDAD_VALENCIANA: 12,
  ANDALUCIA: 15,
  ISLAS_BALEARES: 13,
  MURCIA: 16,
  CEUTA: 18,
  MELILLA: 19,
} as const;
