import { User } from '@type/admin/user.interface';

export const USERS_MOCK: User[] = [
  {
    userId: 1,
    nombre: 'Juan',
    apellidos: 'Pérez',
    email: 'juan.perez@example.com',
    username: 'jperez',
    password: 'hashedPassword1',
    telefono: '555-0101',
    fechaCreacion: new Date('2024-01-01'),
    fechaActualizacion: new Date('2024-01-01'),
    activo: false,
    roles: ['OPERADOR_SIGEMAD', 'ADMINISTRADOR'],
  },
  {
    userId: 2,
    nombre: 'María',
    apellidos: 'García',
    email: 'maria.garcia@example.com',
    username: 'mgarcia',
    password: 'hashedPassword2',
    telefono: '555-0102',
    fechaCreacion: new Date('2024-01-02'),
    fechaActualizacion: new Date('2024-01-02'),
    activo: true,
    roles: ['OPERADOR_OPE'],
  },
  {
    userId: 3,
    nombre: 'Carlos',
    apellidos: 'López',
    email: 'carlos.lopez@example.com',
    username: 'clopez',
    password: 'hashedPassword3',
    telefono: '555-0103',
    fechaCreacion: new Date('2024-01-03'),
    fechaActualizacion: new Date('2024-01-03'),
    activo: true,
    roles: ['ADMINISTRADOR'],
  },
  {
    userId: 4,
    nombre: 'Ana',
    apellidos: 'Martínez',
    email: 'ana.martinez@example.com',
    username: 'amartinez',
    password: 'hashedPassword4',
    telefono: '555-0104',
    fechaCreacion: new Date('2024-01-04'),
    fechaActualizacion: new Date('2024-01-04'),
    activo: true,
    roles: ['LECTURA_SIGEMAD'],
  },
  {
    userId: 5,
    nombre: 'Roberto',
    apellidos: 'Sánchez',
    email: 'roberto.sanchez@example.com',
    username: 'rsanchez',
    password: 'hashedPassword5',
    telefono: '555-0105',
    fechaCreacion: new Date('2024-01-05'),
    fechaActualizacion: new Date('2024-01-05'),
    activo: true,
    roles: ['GESTOR_OPE'],
  },
  {
    userId: 6,
    nombre: 'Laura',
    apellidos: 'Fernández',
    email: 'laura.fernandez@example.com',
    username: 'lfernandez',
    password: 'hashedPassword6',
    telefono: '555-0106',
    fechaCreacion: new Date('2024-01-06'),
    fechaActualizacion: new Date('2024-01-06'),
    activo: true,
    roles: ['GESTOR_SIGEMAD'],
  },
  {
    userId: 7,
    nombre: 'Miguel',
    apellidos: 'Rodríguez',
    email: 'miguel.rodriguez@example.com',
    username: 'mrodriguez',
    password: 'hashedPassword7',
    telefono: '555-0107',
    fechaCreacion: new Date('2024-01-07'),
    fechaActualizacion: new Date('2024-01-07'),
    activo: true,
    roles: ['ADMINISTRADOR'],
  },
  {
    userId: 8,
    nombre: 'Sofía',
    apellidos: 'Gómez',
    email: 'sofia.gomez@example.com',
    username: 'sgomez',
    password: 'hashedPassword8',
    telefono: '555-0108',
    fechaCreacion: new Date('2024-01-08'),
    fechaActualizacion: new Date('2024-01-08'),
    activo: true,
    roles: ['OPERADOR_OPE'],
  },
  {
    userId: 9,
    nombre: 'David',
    apellidos: 'Hernández',
    email: 'david.hernandez@example.com',
    username: 'dhernandez',
    password: 'hashedPassword9',
    telefono: '555-0109',
    fechaCreacion: new Date('2024-01-09'),
    fechaActualizacion: new Date('2024-01-09'),
    activo: true,
    roles: ['OPERADOR_SIGEMAD'],
  },
  {
    userId: 10,
    nombre: 'Elena',
    apellidos: 'Díaz',
    email: 'elena.diaz@example.com',
    username: 'ediaz',
    password: 'hashedPassword10',
    telefono: '555-0110',
    fechaCreacion: new Date('2024-01-10'),
    fechaActualizacion: new Date('2024-01-10'),
    activo: true,
    roles: ['LECTURA_SIGEMAD'],
  },
  {
    userId: 11,
    nombre: 'Javier',
    apellidos: 'Moreno',
    email: 'javier.moreno@example.com',
    username: 'jmoreno',
    password: 'hashedPassword11',
    telefono: '555-0111',
    fechaCreacion: new Date('2024-01-11'),
    fechaActualizacion: new Date('2024-01-11'),
    activo: true,
    roles: ['GESTOR_OPE'],
  },
  {
    userId: 12,
    nombre: 'Carmen',
    apellidos: 'Álvarez',
    email: 'carmen.alvarez@example.com',
    username: 'calvarez',
    password: 'hashedPassword12',
    telefono: '555-0112',
    fechaCreacion: new Date('2024-01-12'),
    fechaActualizacion: new Date('2024-01-12'),
    activo: true,
    roles: ['GESTOR_SIGEMAD', 'ADMINISTRADOR'],
  },
  {
    userId: 13,
    nombre: 'Pablo',
    apellidos: 'Jiménez',
    email: 'pablo.jimenez@example.com',
    username: 'pjimenez',
    password: 'hashedPassword13',
    telefono: '555-0113',
    fechaCreacion: new Date('2024-01-13'),
    fechaActualizacion: new Date('2024-01-13'),
    activo: true,
    roles: ['ADMINISTRADOR'],
  },
  {
    userId: 14,
    nombre: 'Isabel',
    apellidos: 'Ruiz',
    email: 'isabel.ruiz@example.com',
    username: 'iruiz',
    password: 'hashedPassword14',
    telefono: '555-0114',
    fechaCreacion: new Date('2024-01-14'),
    fechaActualizacion: new Date('2024-01-14'),
    activo: true,
    roles: ['OPERADOR_OPE'],
  },
  {
    userId: 15,
    nombre: 'Antonio',
    apellidos: 'Serrano',
    email: 'antonio.serrano@example.com',
    username: 'aserrano',
    password: 'hashedPassword15',
    telefono: '555-0115',
    fechaCreacion: new Date('2024-01-15'),
    fechaActualizacion: new Date('2024-01-15'),
    activo: true,
    roles: ['OPERADOR_SIGEMAD'],
  },
  {
    userId: 16,
    nombre: 'Lucía',
    apellidos: 'Torres',
    email: 'lucia.torres@example.com',
    username: 'ltorres',
    password: 'hashedPassword16',
    telefono: '555-0116',
    fechaCreacion: new Date('2024-01-16'),
    fechaActualizacion: new Date('2024-01-16'),
    activo: true,
    roles: ['LECTURA_SIGEMAD'],
  },
  {
    userId: 17,
    nombre: 'Francisco',
    apellidos: 'Ramírez',
    email: 'francisco.ramirez@example.com',
    username: 'framirez',
    password: 'hashedPassword17',
    telefono: '555-0117',
    fechaCreacion: new Date('2024-01-17'),
    fechaActualizacion: new Date('2024-01-17'),
    activo: true,
    roles: ['ADMINISTRADOR'],
  },
  {
    userId: 18,
    nombre: 'Marta',
    apellidos: 'Flores',
    email: 'marta.flores@example.com',
    username: 'mflores',
    password: 'hashedPassword18',
    telefono: '555-0118',
    fechaCreacion: new Date('2024-01-18'),
    fechaActualizacion: new Date('2024-01-18'),
    activo: true,
    roles: ['GESTOR_OPE'],
  },
  {
    userId: 19,
    nombre: 'Diego',
    apellidos: 'Cruz',
    email: 'diego.cruz@example.com',
    username: 'dcruz',
    password: 'hashedPassword19',
    telefono: '555-0119',
    fechaCreacion: new Date('2024-01-19'),
    fechaActualizacion: new Date('2024-01-19'),
    activo: true,
    roles: ['GESTOR_SIGEMAD'],
  },
  {
    userId: 20,
    nombre: 'Patricia',
    apellidos: 'Ortega',
    email: 'patricia.ortega@example.com',
    username: 'portega',
    password: 'hashedPassword20',
    telefono: '555-0120',
    fechaCreacion: new Date('2024-01-20'),
    fechaActualizacion: new Date('2024-01-20'),
    activo: true,
    roles: ['OPERADOR_SIGEMAD'],
  },
];
