INSERT INTO OPE_Menu (Id, Nombre, Tipo, IdGrupo, NumOrden, Ruta, Icono, ColorRgb) VALUES
(1, 'Datos', 'grupo', 0, 1, NULL, NULL, NULL),
(2, 'Embarques diarios', 'item', 1, 1, '/ope/datos/embarques-diarios', '', ''),
(3, 'Asistencias', 'item', 1, 2, '/ope/datos/asistencias', '', ''),
(4, 'Fronteras', 'item', 1, 3, '/ope/datos/fronteras', '', ''),
(5, 'Afluencia a puntos de control en carreteras', 'item', 1, 4, '/ope/datos/afluencia-puntos-control-carreteras', '', ''),
(6, 'Áreas de descanso y puntos de información en carreteras', 'item', 1, 5, '/ope/datos/areas-descanso', '', ''),
(7, 'Ocupación de áreas de estacionamiento', 'item', 1, 6, '/ope/datos/areas-estacionamiento', '', ''),
(8, 'Informes', 'grupo', 0, 2, NULL, NULL, NULL),
(9, 'Informe de prueba', 'item', 8, 1, '/ope/ope-informes-prueba', '', ''),
(10, 'Planificación', 'grupo', 0, 3, NULL, NULL, NULL),
(11, 'Plan de flota', 'item', 10, 1, '/ope/ope-planificacion-plan-flota', '', ''),
(12, 'Participantes AGE', 'item', 10, 2, '/ope/ope-planificacion-participantes-age', '', ''),
(13, 'Incidencias', 'grupo', 0, 4, NULL, NULL, NULL),
(14, 'Incidencias. Datos de inicio', 'item', 13, 1, '/ope/ope-incidencias-datos-inicio', '', ''),
(15, 'APBA', 'grupo', 0, 5, NULL, NULL, NULL),
(16, 'Entrada de vehículos en puertos APBA', 'item', 15, 1, '/ope/ope-apba-entrada-vehiculos-puertos', '', ''),
(17, 'Embarques de vehículos en APBA por intervalos horarios', 'item', 15, 2, '/ope/ope-apba-embarques-vehiculos-intervalos-horarios', '', ''),
(18, 'Administración OPE', 'grupo', 0, 6, NULL, NULL, NULL),
(19, 'Periodos', 'item', 18, 1, '/ope/administracion/periodos', '/assets/img/other-risks.svg', '169, 169, 169'),
(20, 'Puertos', 'item', 18, 2, '/ope/administracion/puertos', '/assets/img/config.svg', '169, 169, 169'),
(21, 'Líneas marítimas', 'item', 18, 3, '/ope/administracion/lineas-maritimas', '/assets/img/config.svg', '169, 169, 169'),
(22, 'Fronteras', 'item', 18, 4, '/ope/administracion/fronteras', '/assets/img/config.svg', '169, 169, 169'),
(23, 'Puntos de control en carreteras', 'item', 18, 5, '/ope/administracion/puntos-control-carreteras', '', ''),
(24, 'Áreas de descanso y puntos de información en carreteras', 'item', 18, 6, '/ope/administracion/areas-descanso', '', ''),
(25, 'Áreas de estacionamiento', 'item', 18, 7, '/ope/administracion/areas-estacionamiento', '', ''),
(26, 'Porcentajes de ocupación de áreas de estacionamiento', 'item', 18, 8, '/ope/administracion/porcentajes-ocupacion-areas-estacionamiento', '', ''),
(27, 'Catálogo', 'item', 18, 9, '/ope/administracion/catalogo/3', '', ''),
(28, 'Log', 'item', 18, 10, '/ope/administracion/log/4', '', ''),
(29, 'Histórico SIGE2', 'item', 18, 11, '/ope/administracion/historico-sige-2/5', '', '');
